### ISSUE TITLE
Issue with check

### ISSUE THREAD

**Issue by Frequinzy** [INDAPlus21/murnion-chess#2]
From testing in [my chess engine](https://github.com/INDAPlus21/emilhul-chess-gui) I've found that checks do not work properly. The first issue is that black pieces are not allowed to move to a square where they check the white king.
Ex.
![image](https://user-images.githubusercontent.com/90456354/136431852-9ccd4c2f-0136-4550-af55-18b0988a89a8.png)

The second issue is that black is allowed to do any move even if the black king is in check (This might happen for the white king as well, but I can't check due to the first issue.)
Ex.
![image](https://user-images.githubusercontent.com/90456354/136432386-461ae307-ad20-4086-ac8c-16847d34a238.png)

**Comment by Frequinzy** [comment]
Regarding the second issue, I think the white king work as intended. At least it's not possible to move it to a threatened square.

**Comment by abdbla** [comment]
Fixed in the latest commit! Turns out it was a combination of pawns threatening incorrectly for white pieces, and the game always assuming its white turn to move when checking for check.
